server:
  port: 8082
  servlet:
    context-path: /resource-server-opaque

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://localhost:8080/realms/foorealm/protocol/openid-connect/token/introspect
          introspection-client-id: barClient
          introspection-client-secret: vSoKtoK496evMSuTtj8yrly8bUJIE7xf

logging:
  level:
    org:
      springframework:
        security: DEBUG
